apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: unpack-pipeline-
spec:
  entrypoint: main
  templates:
    - name: main

      steps:
        # download tarball of data to be prepped for processing.
      - - name: Download-tarball
          template: download-tarball
    
    - name: download-tarball
      script:
        image: alpine:3.23.4
        command: ["/bin/sh", "-c"]
        source: |
          echo "Download tarball function"
          wget -h
