# CRD that works on unpacking and tracking of files
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hello-brikat  # Name of this Workflow
spec:
  entrypoint: hello-brikat     # Defines "hello-world" as the "main" template
  templates:
  - name: hello-brikat         # Defines the "hello-world" template
    container:
      image: busybox
      command: [echo]
      args: ["hello world brikats"]   # This template runs "echo" in the "busybox" image with arguments "hello world"