# The Sensor listens to the designated EventSource and parameterizes the event data (like bucket name and file name) to trigger an explicit Argo Workflow.
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: minio-sensor
  namespace: argo-events
spec:
  dependencies:
    - name: minio-dep
      eventSourceName: minio-event-source
      eventName: argo-worflow
  triggers:
    - template:
        name: workflow-trigger
        argoWorkflow:
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: minio-triggered-
              spec:
                entrypoint: process-file
                arguments:
                  parameters:
                    - name: bucket
                      value: "my-bucket"
                    - name: file
                      value: "helloworld"
                templates:
                  - name: process-file
                    inputs:
                      parameters:
                        - name: bucket
                        - name: file
                    container:
                      image: alpine:latest
                      command: [sh, -c]
                      args: ["echo Processing file {{inputs.parameters.file}} from bucket {{inputs.parameters.bucket}}"]
          parameters:
            - src:
                dependencyName: minio-dep
                dataKey: notification.0.s3.bucket.name
              dest: spec.arguments.parameters.0.value
            - src:
                dependencyName: minio-dep
                dataKey: notification.0.s3.object.key
              dest: spec.arguments.parameters.1.value
