# The Sensor listens to the designated EventSource and parameterizes the event data (like bucket name and file name) to trigger an explicit Argo Workflow.
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: minio-sensor
  namespace: argo-events
spec:
  template:
    serviceAccountName: operate-workflow-sa
  dependencies:
      # has to be the same name as the event-source
    - name: minio-event-source
      eventSourceName: minio-event-source
      eventName: argo-workflow
  triggers:
    - template:
        name: workflow-trigger
        k8s:
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: minio-triggered-workflow-
              spec:
                entrypoint: main
                templates:
                  - name: main
                    container:
                      image: alpine:latest
                      command: [echo]
                      args: ["File uploaded to MinIO!"]
