apiVersion: v1
kind: Secret
metadata:
  name: minio-creds
  namespace: argo-events
type: Opaque
stringData:
  accesskey: "access-key-created-from-minio-bucket-console"
  secretkey: "secrets-key-created-from-minio-bucket-console"